swagger: '2.0'
info:
  description: OAuth API
  version: 1.0
  title: OAuth API
  # put the contact info for your development or API team
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/api-manager/"
    email: "architecture@wso2.com"

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
  - https
host: localhost
basePath: /api/auth/oauth2/v1.0

paths:
  /authorize:
    get:
      tags:
      - OAuth Authorization
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/x-www-form-urlencoded
      parameters:
      - in: query
        name: response_type
        description: Expected response type
        required: true
        type: string
      - in: query
        name: client_id
        description: OAuth client identifier
        required: true
        type: string
      - in: query
        name: redirect_uri
        description: Clients redirection endpoint
        type: string
      - in: query
        name: scope
        description: OAuth scopes
        type: string
      - in: query
        name: state
        description: Opaque value used by the client to maintain
         state between the request and callback
        type: string
      responses:
        302:
          description: Response from authorization endpoint
          headers:
            Location:
              type: string

  /token:
    post:
      tags:
      - OAuth Token
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Authentication scheme header
          type: string
        - in: formData
          name: grant_type
          description: Required OAuth grant type
          required: true
          type: string
        - in: formData
          name: code
          description: Authorization code to be sent for authorization grant type
          type: string
        - in: formData
          name: redirect_uri
          description: Clients redirection endpoint
          type: string
        - in: formData
          name: client_id
          description: OAuth client identifier
          type: string
        - in: formData
          name: client_secret
          description: OAuth client secret
          type: string
        - in: formData
          name: refresh_token
          description: Refresh token issued to the client.
          type: string
        - in: formData
          name: scope
          description: OAuth scopes
          type: string
        - in: formData
          name: username
          description: username
          type: string
        - in: formData
          name: password
          description: password
          type: string
        - in: formData
          name: validity_period
          description: Validity period of token
          type: integer
          format: int64
      responses:
        200:
          description: |
            OK.
            Successful response from token endpoint.
          schema:
            $ref: '#/definitions/TokenResponse'
          headers:
            Content-Type:
              description: |
                The content type of the body.
              type: string
        400:
          description: |
            Bad Request.
            Error response from token endpoint due to malformed request.
          schema:
            $ref: '#/definitions/TokenErrorResponse'
          headers:
            Content-Type:
              description: |
                The content type of the body.
              type: string
        401:
          description: |
            Unauthorized.
            Error response from token endpoint due to client authentication failure.
          schema:
            $ref: '#/definitions/TokenErrorResponse'
          headers:
            Content-Type:
              description: |
                The content type of the body.
              type: string

  /userinfo:
     get:
       tags:
       - OAuth Userinfo
       consumes:
       - application/x-www-form-urlencoded
       produces:
       - application/json
       parameters:
       - in: header
         name: Authorization
         description: Authentication scheme header
         required: true
         type: string
       - in: query
         name: schema
         description: Schema value
         required: true
         type: string
       responses:
         200:
           description: |
             OK.
             Successful response from userinfo endpoint.
           type: string
           headers:
             Content-Type:
               description: |
                 The content type of the body.
               type: string
         400:
           description: |
             Bad Request.
             Error response from userinfo endpoint due to malformed request.
           schema:
             $ref: '#/definitions/Error'
           headers:
             Content-Type:
               description: |
                 The content type of the body.
               type: string
         401:
           description: |
             Unauthorized.
             Error response from userinfo endpoint due to client authentication failure.
           schema:
             $ref: '#/definitions/Error'
           headers:
             Content-Type:
               description: |
                 The content type of the body.
               type: string

definitions:
  TokenResponse:
    title: Successful response sent for OAuth token request.
    required:
      - access_token
      - token_type
    properties:
      access_token:
        type: string
        description: |
          OAuth access tokn issues by authorization server.
      token_type:
        type: string
        description: |
          The type of the token issued.
      expires_in:
        type: integer
        format: int64
        description: |
          The lifetime in seconds of the access token.
      refresh_token:
        type: string
        description: |
          OPTIONAL.
          The refresh token, which can be used to obtain new access tokens.
      scope:
        type: string
        description: |
          The scope of the access token requested.

  TokenErrorResponse:
    title: Error response sent for OAuth token request.
    required:
      - preProcessingError
    properties:
      preProcessingError:
        type: string
        description: |
          Error code classifying the type of preProcessingError.

  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string
